Update CHANGELOG
nlesc-recruit/CUDA-wrappers pull request #42
Opened 2022-02-21 10:58 UTC by abelsiqueira

Updating the CHANGELOG for future updates.

2022-02-21 11:30 UTC, jspaaks commented on CHANGELOG.md
> +[0.1.0]: https://github.com/nlesc-recruit/CUDA-wrappers/releases/tag/v0.1.0
```suggestion
[Unreleased]: https://github.com/nlesc-recruit/CUDA-wrappers/compare/0.1.0...HEAD
[0.1.0]: https://github.com/nlesc-recruit/CUDA-wrappers/releases/tag/0.1.0
```

2022-02-21 11:32 UTC, jspaaks commented on CHANGELOG.md
> +- First release with existing code.
Not sure if it is required, but I like having newlines between section headings and content

2022-02-21 11:33 UTC, jspaaks requested changes
minor thing about the tags, as well as a note about markdown style

2022-02-21 13:04 UTC, abelsiqueira commented on CHANGELOG.md
> +[0.1.0]: https://github.com/nlesc-recruit/CUDA-wrappers/releases/tag/v0.1.0
Nice catch.

2022-02-21 13:14 UTC, abelsiqueira commented
Thanks for the review. I have fixed the issues you mentioned.

2022-02-23 08:35 UTC, jspaaks approved these changes
All good!

2022-02-23 08:42 UTC, abelsiqueira commented
Thanks for the review

2022-02-23 08:42 UTC, merged