[WIP] Adapt linters from Schaapcommon repo
nlesc-recruit/CUDA-wrappers pull request #59
Opened 2022-02-24 13:16 UTC by abelsiqueira

**Description**

Adapt linters from [Schaapcommon](https://git.astron.nl/RD/schaapcommon) repo and create GitHub workflow using them.

**Related issues**:

- #23 

**Instructions to review the pull request**

In progress

2022-02-28 14:20 UTC, jspaaks commented
Hi Abel, nice work on this. What do you think about adding the install instructions for cmakelang, clang-tidy, clan-format to the developer documentation `README.dev.md` following Bouwe's suggestion?

2022-02-28 14:40 UTC, abelsiqueira commented
> Hi Abel, nice work on this. What do you think about adding the install instructions for cmakelang, clang-tidy, clan-format to the developer documentation `README.dev.md` following Bouwe's suggestion?

Issue #32 touches that already.

2022-02-28 14:50 UTC, bouweandela commented
Why do you need so many configuration files if you're using the defaults?

2022-02-28 15:08 UTC, abelsiqueira commented
> Why do you need so many configuration files if you're using the defaults?

So the choices are explicit. Otherwise, the software will look for configuration files in whatever other places and that can lead to different results. The commands to generate these are in the files.

2022-02-28 15:31 UTC, fdiblen requested changes
thank you @abelsiqueira 

When I run `make -C build clang-lint` I get the error below.

```
make: Entering directory '/tmp/tmp.K30e8g7bzm/build'
make: *** No rule to make target 'clang-lint'.  Stop.
make: Leaving directory '/tmp/tmp.K30e8g7bzm/build'
```

Maybe we are missing a configuration for the linter?

2022-02-28 15:54 UTC, abelsiqueira commented
Nice catch. Apparently, this is a bug with empty CMakeLists.txt in `usage-examples`. This can be verified with
```
cmake-lint usage-examples/plain-copy/CMakeLists.txt
```
While for the root CMakeLists.txt it will work normally. Notice that `cmake-format` fixes the empty CMakeLists.txt to have a single empty line, so running these in order, like I did, does not reveal this error.

2022-02-28 16:41 UTC, abelsiqueira commented
> Including the generated files has the downside that changes to the default configuration will not be picked up as the linter/formatter is updated. Is that intentional? Or would it be better to e.g. just tell clang-format to use Google style instead of the Google style dumped to a configuration file?

Intentional. If I have a different version than you and we rely on the versions' default then we have different results. Also, I expected that ASTRON has some specific style, so this can also be seen as a placeholder for their choices.

2022-03-01 13:07 UTC, fdiblen commented on .github/workflows/codacy-analysis.yml
> +  codacy-analysis-cli:
```suggestion
  codacy:
```

2022-03-01 13:07 UTC, fdiblen commented on .github/workflows/codacy-analysis.yml
> +    name: Codacy Analysis CLI
```suggestion
    name: Codacy
```

2022-03-01 15:31 UTC, abelsiqueira commented on .github/workflows/codacy.yml
> +          cmake -S . -B build
These options do not have long versions

2022-03-01 15:31 UTC, abelsiqueira commented on .github/workflows/codacy.yml
> +      # COMMIT variable defined below was taken from codacy-analysis-cli-action
Explaining where did `COMMIT` came from.

2022-03-01 15:32 UTC, abelsiqueira commented on cmake/linter-tools.cmake
> +    -i
This does not have a long form.

2022-03-01 15:36 UTC, abelsiqueira commented on cmake/linter-tools.cmake
> +    ${INCLUDE_DIRECTORIES}
`--` separates options for `clang-tidy` and options for the compiler.
Maybe `INCLUDE_DIRECTORIES` can be reused in the compilation of the rest of the library, but it is probably best discussed in a different issue.

2022-03-01 15:52 UTC, abelsiqueira commented
@fdiblen, I looked into the `clang-tidy` variables, and it needs to build the library to work properly. That is why it needs `INCLUDE_DIRECTORIES`. However, I did not set INCLUDE_DIRECTORIES correctly.
At the moment, I am still not sure that Codacy + Clang-tidy is working properly, but I hope the other issues were addressed. Please let me know.

2022-03-01 16:47 UTC, fdiblen approved these changes
Looks good. Thanks @abelsiqueira :stew:

2022-03-01 16:49 UTC, abelsiqueira commented
Thanks for the review :rice:

2022-03-01 16:49 UTC, merged